"""empty message

Revision ID: 849e20aefec0
Revises: a5cffa318ac2
Create Date: 2024-04-08 22:31:20.226572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849e20aefec0'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Director',
    sa.Column('directo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('directo_id')
    )
    op.create_table('Gender',
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('gender_id')
    )
    op.create_table('Planet',
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('terrain', sa.String(length=250), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('planet_id')
    )
    op.create_table('Specie',
    sa.Column('specie_id', sa.Integer(), nullable=False),
    sa.Column('languaje', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('specie_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.Column('suscription_dates', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('favorites', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vehicle',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('model', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('Film',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('opening', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['Director.directo_id'], ),
    sa.PrimaryKeyConstraint('film_id')
    )
    op.create_table('Favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['Film.film_id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['Planet.planet_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('People',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('specie_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['Film.film_id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['Gender.gender_id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['Planet.planet_id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['Specie.specie_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['Vehicle.vehicle_id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('Starship',
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['People.character_id'], ),
    sa.PrimaryKeyConstraint('starship_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('Starship')
    op.drop_table('People')
    op.drop_table('Favorite')
    op.drop_table('Film')
    op.drop_table('Vehicle')
    op.drop_table('User')
    op.drop_table('Specie')
    op.drop_table('Planet')
    op.drop_table('Gender')
    op.drop_table('Director')
    # ### end Alembic commands ###
